---

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABSE}
      - MYSQL_USER=${MYSQL_USER}

  app:
    image: nextcloud
    restart: always
    networks:
      - "tailnet"       
    labels:
      - traefik.enable=true
      ## Redirect to HTTPS
      - traefik.http.routers.cloud-https.tls=true
      - traefik.http.routers.cloud-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.cloud-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.cloud-https.rule=Host(`${CLOUD_DOMAIN}`)
      - traefik.http.services.cloud-https.loadbalancer.server.port=80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}


  # tailscale-nextcloud:
  #   image: tailscale/tailscale:latest
  #   container_name: ts-nextcloud
  #   hostname: cloud
  #   networks:
  #     - "tailnet"       
  #   dns:
  #    - "8.8.8.8"
  #   environment:
  #     - TS_AUTHKEY=${CLOUD_TS_AUTH_KEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:container
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_SERVE_CONFIG=/config/nextcloud.json
  #     - TS_USERSPACE=false

  #   volumes:
  #     - ${CFG_PATH}/tailscale/tailscale-nextcloud/state:/var/lib/tailscale
  #     - ${CFG_PATH}/tailscale/tailscale-nextcloud/config:/config
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #     - net_admin
  #     - sys_module
  #   restart: unless-stopped


networks:
  tailnet:
    external:
      name: tailnet