version: '3.3'
services:
  adguard:
      image: adguard/adguardhome:latest
      container_name: adguardhome
      restart: unless-stopped
      ports:  # Map container ports to host ports
        # Expose port 53 on TCP and UDP for DNS queries
        - "53:53/tcp"
        - "53:53/udp"

        # Expose port 67 on UDP for DHCP server
        - "67:67/udp"

        # Expose port 68 on UDP for DHCP client
        # - "68:68/udp"

        # Expose port 443 on TCP and UDP for HTTPS web interface
        - "443:443/tcp"
        - "443:443/udp"

        # Expose port 3000 on TCP for AdGuard Home's API
        - "3000:3000/tcp"

        # Expose port 853 on TCP for DNS-over-TLS (DoT)
        - "853:853/tcp"

        # Expose port 784 on UDP for DNS-over-QUIC (DoQ)
        - "784:784/udp"

        # Expose port 853 on UDP for DNS-over-DTLS (DoT)
        - "853:853/udp"

        # Expose port 8853 on UDP for DNS-over-TLS (DoT)
        - "8853:8853/udp"

        # Expose port 5443 on TCP and UDP for DNSCrypt
        - "5443:5443/tcp"
        - "5443:5443/udp"
      labels:
        - traefik.enable=true
        ## Redirect to HTTPS
        - traefik.http.routers.adguard-https.tls=true
        - traefik.http.routers.adguard-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
        - traefik.http.routers.adguard-https.entrypoints=${TRAEFIK_ENTRYPOINT}
        - traefik.http.routers.adguard-https.rule=Host(`adguard.${DOMAIN}`)
        - traefik.http.services.adguard-https.loadbalancer.server.port=80
      volumes:
          - ${CFG_PATH}/adguardData:/opt/adguardhome/work
          - ${CFG_PATH}/adguard:/opt/adguardhome/conf
      networks:
        - "tailnet"  
  # tailscale-adguard:
  #   image: tailscale/tailscale:latest
  #   container_name: ts-adguard
  #   hostname: adguard
  #   networks:
  #     - "tailnet"       
  #   dns:
  #    - "1.1.1.1"
  #   environment:
  #     - TS_AUTHKEY=${ADGUARD_TS_AUTH_KEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:container
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_SERVE_CONFIG=/config/adguard.json
  #     - TS_USERSPACE=false
  #   volumes:
  #     - ${CFG_PATH}/tailscale/tailscale-adguard/state:/var/lib/tailscale
  #     - ${CFG_PATH}/tailscale/tailscale-adguard/config:/config
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #     - net_admin
  #     - sys_module
  #   restart: unless-stopped


networks:
  tailnet:
    external:
      name: tailnet
