---
services:
  web:
    image: ansible/awx:17.1.0
    container_name: awx_web
    networks:
      - "tailnet"
    labels:
      - traefik.enable=true
    ## the container's port must be the same with the STASH_PORT in the environment section
      - traefik.http.routers.awx.tls=true
      - traefik.http.routers.awx.tls.certresolver=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.awx.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.awx.rule=Host(`${AWX_DOMAIN}`)
      - traefik.http.services.awx.loadbalancer.server.port=80
    depends_on:
      - redis
      - postgres
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ${CFG_PATH}/awx/SECRET_KEY:/etc/tower/SECRET_KEY
      - ${CFG_PATH}/environment.sh:/etc/tower/conf.d/environment.sh"
      - ${CFG_PATH}/credentials.py:/etc/tower/conf.d/credentials.py"
      - ${CFG_PATH}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - ${CFG_PATH}/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx:17.1.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      -  ${CFG_PATH}/SECRET_KEY:/etc/tower/SECRET_KEY"
      -  ${CFG_PATH}/environment.sh:/etc/tower/conf.d/environment.sh"
      -  ${CFG_PATH}/credentials.py:/etc/tower/conf.d/credentials.py"
      -  ${CFG_PATH}/redis_socket:/var/run/redis/:rw"
    environment:
      AWX_SKIP_MIGRATIONS: "1"
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

networks:
  tailnet:
    external: true