---
services:
    rdtclient:
        image: rogerfar/rdtclient:latest
        container_name: rdtclient
        labels:
            - "traefik.enable=true"
            # Redirect to https
            - traefik.http.routers.rdt-https.tls=true
            - traefik.http.routers.rdt-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
            - traefik.http.routers.rdt-https.entrypoints=${TRAEFIK_ENTRYPOINT}
            - traefik.http.routers.rdt-https.rule=Host(`${RDT_DOMAIN}`)
            - traefik.http.services.rdt-https.loadbalancer.server.port=6500
            - traefik.port=6500
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - ${DATA_PATH}/rdt/:/data/downloads
            - ${DATA_PATH}/rdt/db:/data/db
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        healthcheck:
            test: curl --fail http://localhost:6500 || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s
        network_mode: container:vpn-global
networks:
    tailnet:
        external: true
