services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn-nzb
    hostname: nzb
    dns:
     - "8.8.8.8"
     - "100.100.100.100"
    cap_add:
      - net_admin
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASS}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    networks:
      - "tailnet"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    dns:
      - "1.1.1.1"
    networks: 
      - tailnet 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${CFG_PATH}/sabnzbd/config:/config
      - ${DATA_PATH}:/downloads #optional
      - ${DATA_PATH}/incomplete/nzb:/incomplete-downloads #optional
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.sabnzbd-https.tls=true
      - traefik.http.routers.sabnzbd-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.sabnzbd-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.sabnzbd-https.rule=Host(`${SABNZBD_DOMAIN}`)
      - traefik.http.services.sabnzbd-https.loadbalancer.server.port=8080
      - traefik.port=8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks: 
      - tailnet 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.http.routers.sonarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.sonarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.sonarr-https.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.services.sonarr-https.loadbalancer.server.port=8989
      - traefik.port=8989
    volumes:
      - ${CFG_PATH}/sonarr/data:/config
      - ${DATA_PATH}:/tv #optional
      - ${DATA_PATH}/incomplete/nzb:/downloads #optional
    restart: unless-stopped


networks:
  tailnet:
      name: tailnet
      external: true  