---
services:
    vpn:
        image: qmcgaw/gluetun:latest
        container_name: vpn-global
        hostname: vpn
        dns:
            - "1.1.1.1"
            - "100.100.100.100"
        cap_add:
            - net_admin
        environment:
            - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
            - VPN_TYPE=${VPN_TYPE}
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASS}
        networks:
          vpn-test-network:
            ipv4_address: 172.50.0.1
networks:
    vpn-test-network:
        external: true