---
services:
    vpn:
        image: qmcgaw/gluetun:latest
        container_name: vpn-globaö
        hostname: vpn
        dns:
            - "1.1.1.1"
            - "100.100.100.100"
        cap_add:
            - net_admin
        environment:
            - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
            - VPN_TYPE=${VPN_TYPE}
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASS}
            - SERVER_COUNTRIES=${SERVER_COUNTRIES}
        networks:
            - "tailnet"
networks:
    tailnet:
        external: true