---
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest-ultra-lite
    container_name: pdf
    labels:
        - traefik.enable=true
        ## Redirect to HTTPS
        - traefik.http.routers.pdf-https.tls=true
        - traefik.http.routers.pdf-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
        - traefik.http.routers.pdf-https.entrypoints=${TRAEFIK_ENTRYPOINT}
        - traefik.http.routers.pdf-https.rule=Host(`${PDF_DOMAIN}`)
        - traefik.http.services.pdf-https.loadbalancer.server.port=8080
    volumes:
      - ${CFG_PATH}/pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ${CFG_PATH}/pdf/extraConfigs:/configs
#      - ./customFiles:/customFiles/
      - ${CFG_PATH}/pdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    networks:
      - "tailnet"
  # tailscale-pdf:
  #   image: tailscale/tailscale:latest
  #   container_name: ts-pdf
  #   hostname: acrobat
  #   dns:
  #    - "1.1.1.1"
  #   environment:
  #     - TS_AUTHKEY=${PDF_TS_AUTH_KEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:container
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_SERVE_CONFIG=/config/stirling.json
  #     - TS_USERSPACE=false
  #   volumes:
  #     - ${CFG_PATH}/tailscale/tailscale-pdf/state:/var/lib/tailscale
  #     - ${CFG_PATH}/tailscale/tailscale-pdf/config:/config
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #     - net_admin
  #     - sys_module
  #   restart: unless-stopped


networks:
  tailnet:
    external:
      name: tailnet
