---

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    user: ${user}:${group}
    networks:
      - "tailnet"      
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - traefik.enable=true
    ## the container's port must be the same with the STASH_PORT in the environment section
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.plex.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
    environment:
      - 'ADVERTISE_IP=http://192.168.178.146:32400/,${ADVERTISE_DOMAIN}'
      - TZ=Europe/Berlin
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CFG_PATH}/plex:/config
      - ${DATA_PATH}/TV-Shows:${DATA_PATH}/TV-Shows
      - ${DATA_PATH}/documents:${DATA_PATH}/documents
      - ${DATA_PATH}/Movies:${DATA_PATH}/Movies



networks:
  tailnet:
      name: tailnet
      external: true 
