# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
---
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
     - 9999:9999
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:

      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      
      ## Keep configs, scrapers, and plugins here.
      - ${CFG_PATH}/stash/:/root/.stash
      ## Point this at your collection.
      - ${DATA_PATH}/Documents/:/data
      ## This is where your stash's metadata lives
      - ${CFG_PATH}/stash/:/metadata
      ## Any other cache content.
      - ${CFG_PATH}/stash/:/cache
      ## Where to store binary blob data (scene covers, images)
      - ${CFG_PATH}/stash/:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ${CFG_PATH}/stash/:/generated