---
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
    ## the container's port must be the same with the STASH_PORT in the environment section
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.tls.certresolver=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.tdarr.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.tdarr.rule=Host(`${TDARR_DOMAIN}`)
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    networks:
      - tailnet
    ports:
      - 8266:8266 # server port
    environment:
      - TZ=Europe/Berlin
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${CFG_PATH}/tdarr/configs:/app/configs
      - ${CFG_PATH}/tdarrlogs:/app/logs
      - ${DATA_PATH}:/media
      - ${CFG_PATH}/tdarr/tmp:/temp
    devices:
      - /dev/dri:/dev/dri
    

# node example
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/Berlin
      - nodeName=MyExternalNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - ${CFG_PATH}/tdarr/configs:/app/configs
      - ${CFG_PATH}/tdarrlogs:/app/logs
      - ${DATA_PATH}:/media
      - ${CFG_PATH}/tdarr/tmp:/temp

    devices:
      - /dev/dri:/dev/dri


networks:
  tailnet:
    external: true
