---

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:${PLEX_VERSION}
    user: ${user}:${group}
    networks:
      - "tailnet"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.plex.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
    environment:
      - 'ADVERTISE_IP=http://192.168.178.146:32400/,${ADVERTISE_DOMAIN}'
      - TZ=Europe/Berlin
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all
      - VERSION=docker
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    volumes:
      - ${CFG_PATH}/plex:/config
      - ${CFG_PATH}/plex/transcode:/transcode
      - ${DATA_PATH}/Anime:${DATA_PATH}/Anime
      - ${DATA_PATH}/Documents/:${DATA_PATH}/H
      - ${DATA_PATH}/TV-Shows:${DATA_PATH}/TV-Shows
      - ${DATA_PATH}/Movies:${DATA_PATH}/Movies


networks:
  tailnet:
      name: tailnet
      external: true 