---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks: 
      - tailnet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${CFG_PATH}/radarr:/config
      - ${DATA_PATH}:/media
      - ${DATA_PATH}/incomplete/radarr:/downloads

    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.radarr-https.tls=true
      - traefik.http.routers.radarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.radarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.radarr-https.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.services.radarr-https.loadbalancer.server.port=7878
      - traefik.port=7878
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks: 
      - tailnet
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.overseerr-https.tls=true
      - traefik.http.routers.overseerr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.overseerr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.overseerr-https.rule=Host(`${OVERSEERR_DOMAIN}`)
      - traefik.http.services.overseerr-https.loadbalancer.server.port=5055
      - traefik.port=5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${CFG_PATH}/overseerr:/config
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks: 
      - tailnet
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.jackett-https.tls=true
      - traefik.http.routers.jackett-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.jackett-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.jackett-https.rule=Host(`${JACKETT_DOMAIN}`)
      - traefik.http.services.jackett-https.loadbalancer.server.port=9117
      - traefik.port=9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true #
      - RUN_OPTS= #optional
    volumes:
      - ${CFG_PATH}/jackett/data:/config
      - ${DATA_PATH}/incomplete/jackett:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks: 
      - tailnet 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
      - ${CFG_PATH}/prowlarr/data:/config
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.prowlarr-https.tls=true
      - traefik.http.routers.prowlarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.prowlarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.prowlarr-https.rule=Host(`${PROWLARR_DOMAIN}`)
      - traefik.http.services.prowlarr-https.loadbalancer.server.port=9696
      - traefik.port=9696
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: solverr
    networks: 
      - tailnet 
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.solverr-https.tls=true
      - traefik.http.routers.solverr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.solverr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.solverr-https.rule=Host(`${SOLVERR_DOMAIN}`)
      - traefik.http.services.solverr-https.loadbalancer.server.port=8191
      - traefik.port=8191
    restart: unless-stopped 

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks: 
      - tailnet 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.http.routers.sonarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.sonarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.sonarr-https.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.services.sonarr-https.loadbalancer.server.port=8989
      - traefik.port=8989
    volumes:
      - ${CFG_PATH}/sonarr/data:/config
      - ${DATA_PATH}:/media #optional
      - ${DATA_PATH}/incomplete/nzb:/downloads #optional
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: ${user}:${group}
    networks: [tailnet]
    volumes:
      - ${CFG_PATH}/recyclarr:/config
    environment:
      - TZ=Europe/Berlin

  doplarr:
    image: lscr.io/linuxserver/doplarr:latest
    container_name: doplarr
    networks: 
      - tailnet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
      - DISCORD__TOKEN=${DISCORD_TOKEN}
      - OVERSEERR__API=${OVERSEERR_API}
      - OVERSEERR__URL=${OVERSEERR_URL}
      # - RADARR__API=
      # - RADARR__URL=http://localhost:7878
      # - SONARR__API=
      # - SONARR__URL=http://localhost:8989    - DISCORD__MAX_RESULTS=25 #optional
      - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
      - OVERSEERR__DEFAULT_ID= #optional
      - PARTIAL_SEASONS=true #optional
      - LOG_LEVEL=:debug #optional
      - JAVA_OPTS= #optional
    volumes:
      - ${CFG_PATH}/doplarr/config:/config
    restart: unless-stopped

  get_iplayer:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.whisparr-https.tls=true
      - traefik.http.routers.whisparr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.whisparr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.whisparr-https.rule=Host(`whisparr.${DOMAIN}`)
      - traefik.http.services.whisparr-https.loadbalancer.server.port=6969
      - traefik.port=6969
    volumes:
      - ${CFG_PATH}/whisparr/config:/config
      - ${CFG_PATH}/Documents:/downloads
    restart: unless-stopped
networks:
  tailnet:
    external: true  