---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network: 
      - tailnet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${CFG_PATH}/radarr:/config
      - ${DATA_PATH}:/media
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.radarr-https.tls=true
      - traefik.http.routers.radarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.radarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.radarr-https.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.services.radarr-https.loadbalancer.server.port=7878
      - traefik.port=7878
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network: 
      - tailnet
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.overseerr-https.tls=true
      - traefik.http.routers.overseerr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.overseerr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.overseerr-https.rule=Host(`${OVERSEERR_DOMAIN}`)
      - traefik.http.services.overseerr-https.loadbalancer.server.port=5055
      - traefik.port=5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${CFG_PATH}/overseerr:/config
    restart: unless-stopped



networks:
  tailnet:
    external: true
