services:
  imagemaid:
    networks:
      - tailnet 
    image: kometateam/imagemaid:latest
    container_name: imagemaid
    environment:
      - TZ=Europe/Berlin #optional
    volumes:
      - ${CFG_PATH}/imageMaid/config:/config
      - ${CFG_PATH}/plex:/plex
    restart: unless-stopped

networks:
  tailnet:
    external: true