services:
  imagemaid:
    networks:
      - tailnet 
    image: kometateam/imagemaid:latest
    container_name: imagemaid
    environment:
      - PLEX_PATH=${PLEX_PATH}
      - MODE=${MODE}
      - SCHEDULE=${SCHEDULE}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TIMEOUT=${TIMEOUT}
      - SLEEP=${SLEEP}
      - IGNORE_RUNNING=${IGNORE_RUNNING}
      - LOCAL_DB=${LOCAL_DB}
      - USE_EXISTING=${USE_EXISTING}
      - PHOTO_TRANSCODER=${PHOTO_TRANSCODER}
      - EMPTY_TRASH=${EMPTY_TRASH}
      - CLEAN_BUNDLES=${CLEAN_BUNDLES}
      - OPTIMIZE_DB=${OPTIMIZE_DB}
      - TRACE=${TRACE}
      - LOG_REQUESTS=${LOG_REQUESTS}
      - TZ=Europe/Berlin #optional
    volumes:
      - ${CFG_PATH}/imageMaid/config:/config
      - ${CFG_PATH}/plex/Library/Application\ Support/Plex\ Media\ Server:/plex
    restart: unless-stopped

networks:
  tailnet:
    external: true