services:
  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    networks: 
      - tailnet 
    environment:
      - KOMETA_RUN=true
      - KOMETA_OVERLAYS_ONLY=true      
      - TZ=Europe/Berlin #optional
    volumes:
      - ${CFG_PATH}/kometa/:/config
    restart: unless-stopped

networks:
  tailnet:
    external: true  