services:
  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    networks: 
      - tailnet 
    environment:
      - KOMETA_RUN=${KOMETA_RUN}
      - KOMETA_OVERLAYS_ONLY=${KOMETA_OVERLAYS_ONLY}
      - KOMETA_COLLECTIONS_ONLY=${KOMETA_COLLECTIONS_ONLY} 
      - KOMETA_METADATA_ONLY=${KOMETA_METADATA_ONLY}
      - KOMETA_PLAYLISTS_ONLY=${KOMETA_PLAYLISTS_ONLY}
      - KOMETA_OPERATIONS_ONLY=${KOMETA_OPERATIONS_ONLY}
      - TZ=Europe/Berlin #optional
    volumes:
      - ${CFG_PATH}/kometa/:/config
    restart: unless-stopped

networks:
  tailnet:
    external: true  