---
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: watch
    privileged: true
    dns:
      - 1.1.1.1
    stdin_open: true
    tty: true
    container_name: plextraktwatch
    networks: 
      - tailnet
    restart: always
    volumes:
      - ${CFG_PATH}/plexTrakt:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin

networks:
  tailnet:
    external: true