---
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ${CFG_PATH}/plexTrakt:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin