---
services:
  posterr:
    image: petersem/posterr
    container_name: posterr
    labels:
        - traefik.enable=true
        ## Redirect to HTTPS
        - traefik.http.routers.postarr-https.tls=true
        - traefik.http.routers.postarr-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
        - traefik.http.routers.postarr-https.entrypoints=${TRAEFIK_ENTRYPOINT}
        - traefik.http.routers.postarr-https.rule=Host(`postarr.${DOMAIN}`)
        - traefik.http.services.postarr-https.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Berlin
      BASEPATH: ""
    volumes:
      - ${CFG_PATH}/posterr/config:/usr/src/app/config
      - ${CFG_PATH}/posterr/custom:/usr/src/app/public/custom
    restart: unless-stopped