---
services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    user: ${user}:${group}
    environment:
        - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      # Redirect to https
      - traefik.http.routers.crafty-https.tls=true
      - traefik.http.routers.crafty-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.crafty-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.crafty-https.rule=Host(`crafty.${DOMAIN}`)
      - traefik.http.services.crafty-https.loadbalancer.server.port=9443
      - traefik.port=9443
    volumes:
        - ${CFG_PATH}/crafty/logs:/crafty/logs
        - ${CFG_PATH}/crafty/backups:/crafty/backups
        - ${CFG_PATH}/crafty/servers:/crafty/servers
        - ${CFG_PATH}/crafty/config:/crafty/app/config
        - ${CFG_PATH}/crafty/import:/crafty/import
    network_mode: service:tailscale-crafty
    depends_on:
      - tailscale-crafty  

  tailscale-crafty:
      image: tailscale/tailscale:latest
      container_name: ts-minecraft
      hostname: minecraft
      networks:
        - "tailnet"       
      dns:
        - "8.8.8.8"
      environment:
        - TS_AUTHKEY=${CLOUD_TS_AUTH_KEY}
        - TS_EXTRA_ARGS=--advertise-tags=tag:container
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_SERVE_CONFIG=/config/crafty.json
        - TS_USERSPACE=false
      volumes:
        - ${CFG_PATH}/tailscale/tailscale-crafty/state:/var/lib/tailscale
        - ${CFG_PATH}/tailscale/tailscale-crafty/config:/config
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
        - sys_module
      devices:
        - /dev/net/tun:/dev/net/tun
      restart: unless-stopped
networks:
  tailnet:
      name: tailnet
      external: true 