version: '3.6' 
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CFG_PATH}/proxy:/data
      - ${CFG_PATH}/letsencrypt:/etc/letsencrypt 
    networks: 
      - mydockernet

networks:
  mydockernet:
    external:
      name: mydockernet
