---
services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - "tailnet"   
      - "external_bridge"
    labels:
      - traefik.enable=true
      ## Redirect to HTTPS
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.traefik-https.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.traefik-https.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik-https.loadbalancer.server.port=8080 
    ports:
      # The HTTP port
      - "80:80"
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - ${CFG_PATH}/traefik/letsencrypt/:/letsencrypt
      - ${CFG_PATH}/traefik/data/traefik.yml:/etc/traefik/traefik.yml
      - ${CFG_PATH}/traefik/dynamic/traefik_dyn.yml:/etc/traefik/traefik_dyn.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # Replace with actual token
networks:
  tailnet:
      name: tailnet
      external: true 
  external_bridge:
      name: external_bridge
      external: true 